TOKEN: thisisatoken
logging:
  level:
    org:
      hibernate:
        type: warn
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:C:/data/exampledb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: false